### ISSUE TITLE
webpack.config

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-4#23]
Файлик не смотрится линтером? Там проблема с отступами и табами

**Comment by Hahahayabanan** [comment]
Напиши ещё где-нибудь каким адресом у тебя dev-server запускается

**Comment by Liquense** [comment]
> Напиши ещё где-нибудь каким адресом у тебя dev-server запускается

на http://localhost:8080/demo-page.html, добавил в ридми
