### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-4#7]
Все требования и стандарты распространяются на оба проекта. Тут тоже нужно использовать pug, scss, БЭМ, и т.д.
Сейчас вся вёрстка в одной куче

![image](https://user-images.githubusercontent.com/43137324/96408622-f11f8800-11f4-11eb-8398-c9be56fe2a66.png)

Здесь точно должен быть controller?

**Comment by Liquense** [comment]
> Здесь точно должен быть controller?

При инициализации плагина возвращается экземпляр контролера, показалось это логичным, потому что он и так выступает управляющей прослойкой и публичные функции у него вроде те же, что и нужны для пользования снаружи

**Comment by Hahahayabanan** [comment]
Best practices jQuery плагинов включает в себя использование data-атрибутов в качестве ещё одного способа инициализации начальных параметров. Используя это можно избежать захардкоженности здесь. Т.е. передавать параметры слайдера в pug

![image](https://user-images.githubusercontent.com/43137324/97398621-f8394b00-1904-11eb-99f4-c3a7fe68cc8b.png)

**Comment by Hahahayabanan** [comment]
Посмотри ещё раз demoPage, сейчас много несоответствий с БЭМ
